package com.example.voicely.util

object Routes {
    const val ADVANCED = "advanced"
    const val QUICK = "quick"
    const val BASIC = "basic"
    const val GETTING_STARTED = "getting-started"
    const val CORE_WORDS = "core-words"
    const val LANGUAGES = "languages"
    const val HOME = "home"
    const val REQUESTS = "requests"
    const val RESPONSE = "response"
    const val STARTER_PHRASES = "starter-phrases"
    const val ABOUT_ME = "about-me"
    const val QUESTIONS = "questions"
    const val UNDERSTANDINGS = "understandings"
    const val WISHES = "wishes"
    const val NEED_HELP = "need-help"
    const val GREETINGS_AND_MANNERS = "greetings-manner"
    const val PEOPLE = "people"
    const val BIG = "big"
    const val THINGS = "things"
    const val EAT = "eat"
    const val PLAY = "play"
    const val GO = "go"
    const val WEAR = "wear"
    const val COLORS = "colors"
    const val SCHOOL = "school"
    const val BODY = "body"
    const val FEELINGS = "feelings"
    const val ACTIONS = "actions"
    const val ANIMALS = "animals"
    const val COUNTING = "counting"
    const val GUJRATI = "gujrati"
    const val MARATHI = "marathi"
    const val KANNADA = "kannada"
    const val TELUGU = "telugu"
    const val HINDI = "hindi"
}